/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.jbdc;
import cat.uvic.teknos.aureus.jdbc.PersonRepository;


import org.example.list.LinkedList;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

public class App {
    public static void main(String[] args) throws SQLException {
        var connection = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/m0486",
                "root",
                "rootpassword"
        );
        var person = new Person();
        person.setId(1);
        person.setFirstName("Albert");
        person.setLastName("Smith");

        var repository = new PersonRepository(connection);
        repository.save(person);
        var people = repository.getAll();
        for (var persona : people) {
            System.out.println(persona.getFirstName());
        }
    }
}