/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation("com.fasterxml.jackson.core:jackson-core:2.18.3")
    implementation("com.mysql:mysql-connector-j:9.3.0")
    implementation(project(":utilities"))

}

application {
    // Define the main class for the application.
    mainClass = "cat.uvic.teknos.dam.aureus"
}
