/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-application-conventions")
}

dependencies {
    implementation(project(":jdbc"))
    implementation(project(":model"))
    implementation(project(":repositories"))
    implementation("com.github.freva:ascii-table:1.8.0")
    implementation("com.mysql:mysql-connector-j:9.3.0")
    implementation(project(":utilities"))
}

application {
    mainClass = "cat.uvic.teknos.dam.aureus.ui.App"
}

tasks.named<JavaExec>("run") {
    standardInput = System.`in`
    systemProperty("file.encoding", "UTF-8")
}

// Configure Javadoc
tasks.javadoc {
    title = "Aureus - Documentación"
    options.encoding = "UTF-8"
    (options as StandardJavadocDocletOptions).apply {
        charset("UTF-8")
        encoding = "UTF-8"
        author(true)
        version(true)
    }
}

tasks.named<Test>("test") {
    enabled = false
}