/*
 * This file was generated by the Gradle 'init' task.
 */
plugins {
    java
}

repositories {
    mavenCentral()
}

tasks.test {
    useJUnitPlatform()
}

dependencies {
    // Dependencias Internas de Aureus
    implementation(project(":model"))
    implementation(project(":repositories"))
    implementation(project(":jpa"))

    // Dependencias HTTP y JSON
    implementation("com.athaydes:rawhttp-core:2.4.0")
    implementation("com.athaydes:rawhttp-cli:2.4.0")
    implementation("com.google.code.gson:gson:2.10.1")

    // Dependencias de testing
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.10.0")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.10.0")
    testImplementation("org.mockito:mockito-core:5.8.0")
}