/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-library-conventions")
    application
}

application {
    mainClass.set("cat.uvic.teknos.dam.aureus.ConsoleApp")
}

tasks.named<JavaExec>("run") {
    standardInput = System.`in`
}

dependencies {
    implementation(project(":model"))
    implementation("com.github.freva:ascii-table:1.8.0")
    implementation("com.athaydes.rawhttp:rawhttp-core:2.6.0")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.20.0")
}