/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-library-conventions")
}

dependencies {
    implementation(project(":model"))
    implementation(project(":repositories"))
    implementation("com.mysql:mysql-connector-j:9.3.0")

    testImplementation("org.junit.jupiter:junit-jupiter-api:5.10.0")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.10.0")

    testImplementation("com.h2database:h2:2.3.232")
}

tasks.test {
    useJUnitPlatform()
    // Ejecutar también tests de integración que terminan en *IT
    include("**/*IT.class", "**/*Test.class", "**/*Tests.class", "**/*TestCase.class")
}
